version: "3.8"

services:
    video-stream:
        image: video-stream
        build:
            context: local-stream
            dockerfile: Dockerfile
        container_name: local-stream
        ports:
            - "4000:80"
        environment:
            - PORT=80
        restart: "no"